CREATE TABLE UpdateByTest (
    Id INT NOT NULL PRIMARY KEY,
	Text VARCHAR(256),
	Time TIMESTAMPTZ
);
GO
INSERT INTO UpdateByTest (Id, Text, Time) VALUES (1, 'Fail', TIMESTAMP '1978-03-08' AT TIME ZONE 'UTC');
GO
